AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.main.handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY 